typography_spectrum: 0.20055885426700115
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.7034475631080568
  lightness: 0.11434154491871595
  saturation: 0.42326377728022635
  rhythmicContrast: 0.3267273379024118
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.4359437879174948
analytics:
  google: null
  facebook: null
  twitter: null
name: Web Gallery
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Site
    url: 'http://aroundtheworldin80rides.com'
    type: external
favicon: null
purpose: []
